[package]
name = "c_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.11.0", default-features = false }
clap = { version = "4.5.54", features = ["derive"]}
rayon = { version = "1.11.0", default-features = false }
tempfile = { version = "3.25.0", default-features = false }
unicode-width = { version = "0.2.2", default-features = false }

[profile.release]
debug = true
